In [ ]:
print("Hello Data Analysis")

Hello Data Analysis


In [6]:
import numpy as np
np.random.seed(0)
arr = np.random.randint(0,20,size=(5,5))
print(arr)
print(arr[arr>10])
arr = np.where(arr>10, 0, arr)
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [9]:
arr = np.array([120,135,110,125,130,140])
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.argmax(arr)+1)
print(np.argmin(arr)+1)

760
126.66666666666667
97.22222222222223
6
3


In [15]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate((A,B))
print(C)
C = np.reshape(C, (2, 3))
print(C)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [30]:
arr = np.array([2,1,2,3,1,4,4])
print(np.argwhere(arr==np.max(arr)).flatten()+1)

[6 7]
